{{- if and .Values.config.enable .Values.config.url}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-cron-job" (include "clash.fullname" .) }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.config.schedule }}
  successfulJobsHistoryLimit: 0 
  jobTemplate:
    spec:
      template:
        spec:   
          restartPolicy: Never
          serviceAccountName: {{ include "clash.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumes: #指的是Pod中的卷
            {{ include "clash.volumes" . | nindent 12 }}
          containers:
          - name: upgrade
            image: curlimages/curl:7.84.0
            command:
              - sh
              - /init/cron.sh
            volumeMounts: #将指定的卷mount到容器指定的位置
              {{ include "clash.volumeMounts" . | nindent 14 }}
{{- end }}