apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clash.fullname" . }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clash.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: #指的是Pod中的卷
        {{ include "clash.volumes" . | nindent 8 }}
      initContainers:
        - name: init
          image: busybox:stable
          command:
            [
              "sh",
              "-c",
              "{{- if .Values.secretFile.predb -}}if [ -f {{.Values.config.path}}/config.yaml ];then wget -O {{.Values.config.path}}/Country.mmdb {{.Values.config.predb}}; fi && {{- end -}}if [ -f /init/config.yaml ];then cp -u /init/config.yaml {{.Values.config.path}}/config.yaml; fi",
            ]

          volumeMounts: 
            {{ include "clash.volumeMounts" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts: #将指定的卷mount到容器指定的位置
            {{ include "clash.volumeMounts" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: p1
              containerPort: 7890
              protocol: TCP
          command: ["/clash","-d","{{.Values.config.path}}"]
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
