apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clash.fullname" . }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clash.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: #指的是Pod中的卷
        {{ include "clash.volumes" . | nindent 8 }}
      initContainers:
        - name: init
          image: busybox:stable
          command:
            - "sh"
            - "-c"
            - |
              unzip -o -d {{ .Values.config.path }}/ui /init/dashboard

              if [ ! -f "{{ .Values.config.path }}/Country.mmdb" ]; then
                if [ -n "{{ .Values.config.predb }}" ]; then
                  echo "Downloading Country.mmdb from {{ .Values.config.predb }}..."
                  wget -q -O "{{ .Values.config.path }}/Country.mmdb" "{{ .Values.config.predb }}"
                  if [ $? -ne 0 ]; then
                    echo "Error: Failed to download Country.mmdb from {{ .Values.config.predb }}"
                    exit 1
                  fi
                else
                  echo "Copying Country.mmdb from /root/.config/clash..."
                  cp "/root/.config/clash/Country.mmdb" "{{ .Values.config.path }}/Country.mmdb"
                  if [ $? -ne 0 ]; then
                    echo "Error: Failed to copy Country.mmdb from /root/.config/clash"
                    exit 1
                  fi
                fi
              else
                echo "Country.mmdb already exists at {{ .Values.config.path }}/Country.mmdb"
              fi

              if [ -f /init/config.yaml ]; then
                cp -u /init/config.yaml {{ .Values.config.path }}/config.yaml
                chmod 644 {{ .Values.config.path }}/config.yaml > /dev/null
              fi
          volumeMounts: 
            {{ include "clash.volumeMounts" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts: #将指定的卷mount到容器指定的位置
            {{ include "clash.volumeMounts" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: p1
              containerPort: 7890
              protocol: TCP
          command: ["/clash","-d","{{.Values.config.path}}","-ext-ui","{{.Values.config.path}}/ui/dashboard/"]
          # command: ["/clash","-ext-ui","{{.Values.config.path}}/ui/dashboard/"]
          livenessProbe:
            tcpSocket:
              port: p1
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: p1
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
