{{- if or (not .Values.config.existingClaim) (eq .Values.config.existingClaim "") }}
# existingClaim 未定义或为空字符串时的逻辑
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-pvc" (include "clash.fullname" .) }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
{{- end -}}