{{- if .Values.secretFile.enable}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-files" (include "basic.fullname" .) }}
  labels:
    {{- include "basic.labels" . | nindent 4 }}
data:
  {{- if .Values.secretFile.datas}}
{{ .Values.secretFile.datas | nindent 2}}
  {{- end }}
{{- end }}