apiVersion: v1
kind: Service
metadata:
  name: {{ include "clash.fullname" . }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "clash.selectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "clash.fullname" . }}-node
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 7890
      targetPort: 7890
      protocol: TCP
      name: pi
  selector:
    {{- include "clash.selectorLabels" . | nindent 4 }}
