apiVersion: v1
kind: Service
metadata:
  name: {{ include "clash.fullname" . }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 7890
      targetPort: 7890
      protocol: TCP
      name: p1
  selector:
    {{- include "clash.selectorLabels" . | nindent 4 }}
