
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clash.fullname" . }}-node
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 7890
      targetPort: 7890
      protocol: TCP
      name: pi
  selector:
    {{- include "clash.selectorLabels" . | nindent 4 }}
