{{- if .Values.configFile.enable}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config-files" (include "basic.fullname" .) }}
  labels:
    {{- include "basic.labels" . | nindent 4 }}
data:
  {{- if .Values.configFile.datas}}
{{ .Values.configFile.datas | nindent 2}}
  {{- end }}
{{- end }}