{{- if and (.Values.service.headless) (eq .Values.service.type "ClusterIP")}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "basic.fullname" . }}-headless
  labels:
    {{- include "basic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  clusterIPs:
    - None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "basic.selectorLabels" . | nindent 4 }}
{{- end}}